### ISSUE TITLE
Это ли попало в wireshark 2.0.0?

### ISSUE THREAD

**Issue by neopaf** [avsej/couchbase-dissector#1]
Или там кто-то параллельно мыслит?
Заранее спасибо за ответ.

**Comment by tleyden** [comment]
I don't speak Russian but I think this is asking the exact same thing I was going to ask -- is the Couchbase dissector (which is awesome, btw) included in the latest release of wireshark?  2.0.1

**Comment by ingenthr** [comment]
@tleyden it is in the latest version

**Comment by avsej** [comment]
@neopaf yes it is in 2.x
